spring.application.name=dropbox
spring.datasource.url=jdbc:postgresql://localhost:5432/drive_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
